name: .NET Docker

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: [a,b,c,d,e,f,g,h,i,j]
    steps:
    - uses: actions/checkout@v2
    - name: Upgrade Chrome browser
      run: |
        sudo apt-get update
        sudo apt-get --only-upgrade install google-chrome-stable

        google-chrome --version
    - uses: getong/mariadb-action@v1.1
      with:
        host port: 3306
        container port: 3306
        character set server: 'utf8'
        collation server: 'utf8_general_ci'
        mariadb version: '10.4.10'
        mysql database: 'some_test'
        mysql root password: 'secretpassword'
        mysql user: 'developer'
        mysql password: 'passwordtoo'
    - name: Sleep 15 seconds
      run: sleep 15
    - uses: getong/rabbitmq-action@v1.2
      with:
        rabbitmq version: '3.8.9-management'
        host port: 5672
        rabbitmq user: 'admin'
        rabbitmq password: 'password'
        rabbitmq vhost: 'vhost_name'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.18.3'
    - name: 'Preparing Frontend checkout'
      uses: actions/checkout@v2
      with:
        repository: microting/eform-angular-frontend
        ref: stable
        path: eform-angular-frontend
    - name: Install dependencies
      run: dotnet restore eform-angular-frontend/eFormAPI/eFormAPI.sln
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(git describe --abbrev=0 --tags | cut -d "v" -f 2)
    - name: Build
      run: dotnet build eform-angular-frontend/eFormAPI/eFormAPI.sln
    - name: Unit Tests
      run: dotnet test --no-restore -c Release -v n eform-angular-frontend/eFormAPI/eFormAPI.Web.Tests/eFormAPI.Web.Tests.csproj
    - name: Integration Tests
      run: dotnet test --no-restore -c Release -v n eform-angular-frontend/eFormAPI/eFormAPI.Web.Integration.Tests/eFormAPI.Web.Integration.Tests.csproj
    - name: NPM Install
      run: cd eform-angular-frontend/eform-client && npm install
    - name: NPM start
      run: cd eform-angular-frontend/eform-client && npm start &
    - name: Sleep 75 seconds
      run: sleep 75
    - name: Dotnet run
      run: dotnet run --project eform-angular-frontend/eFormAPI/eFormAPI.Web/eFormAPI.Web.csproj > dotnet_log 2>&1 &
    - name: Sleep 75 seconds
      run: sleep 75
    - name: Configuration testing
      run: cd eform-angular-frontend/eform-client && npm run testheadless
    - name: testheadless2${{matrix.test}}
      run: cd eform-angular-frontend/eform-client && npm run testheadless2${{matrix.test}}
  outer-inner-resource-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: main
    - name: Upgrade Chrome browser
      run: |
        sudo apt-get update
        sudo apt-get --only-upgrade install google-chrome-stable
        google-chrome --version
    - uses: getong/mariadb-action@v1.1
      with:
        host port: 3306 # Optional, default value is 3306. The port of host
        container port: 3306 # Optional, default value is 3306. The port of container
        character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
        collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
        mariadb version: '10.4.10' # Optional, default value is "latest". The version of the MariaDB
        mysql database: 'some_test' # Optional, default value is "test". The specified database which will be create
        mysql root password: 'secretpassword' # Required if "mysql user" is empty, default is empty. The root superuser password
        mysql user: 'developer' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        mysql password: 'passwordtoo' # Required if "mysql user" exists. The password for the "mysql user"
    - name: Sleep 15 seconds
      run: sleep 15
    - uses: getong/rabbitmq-action@v1.2
      with:
        rabbitmq version: '3.8.9-management'
        host port: 5672
        rabbitmq user: 'admin'
        rabbitmq password: 'password'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.18.3'
    - name: 'Preparing Frontend checkout'
      uses: actions/checkout@v2
      with:
        repository: microting/eform-angular-frontend
        ref: stable
        path: eform-angular-frontend
    - name: 'Preparing items planning checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: microting/eform-angular-outer-inner-resource-plugin
        ref: stable
        path: eform-angular-outer-inner-resource-plugin
    - name: Install dependencies
      run: dotnet restore eform-angular-outer-inner-resource-plugin/eFormAPI/Plugins/OuterInnerResource.Pn/OuterInnerResource.Pn.sln
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3 | cut -d "v" -f 2)
    - name: Build
      run: dotnet build eform-angular-outer-inner-resource-plugin/eFormAPI/Plugins/OuterInnerResource.Pn/OuterInnerResource.Pn.sln
    - name: Unit Tests
      run: dotnet test --no-restore -c Release -v n eform-angular-outer-inner-resource-plugin/eFormAPI/Plugins/OuterInnerResource.Pn/OuterInnerResource.Pn.Test/OuterInnerResource.Pn.Test.csproj
    - name: Copy dependencies
      run: |
        cp -av eform-angular-outer-inner-resource-plugin/eform-client/src/app/plugins/modules/outer-inner-resource-pn eform-angular-frontend/eform-client/src/app/plugins/modules/outer-inner-resource-pn
        cp -av eform-angular-outer-inner-resource-plugin/eform-client/e2e/Tests/outer-inner-resource-settings eform-angular-frontend/eform-client/e2e/Tests/outer-inner-resource-settings
        cp -av eform-angular-outer-inner-resource-plugin/eform-client/e2e/Tests/outer-inner-resource-general eform-angular-frontend/eform-client/e2e/Tests/outer-inner-resource-general
        cp -av eform-angular-outer-inner-resource-plugin/eform-client/e2e/Page\ objects/OuterInnerResource eform-angular-frontend/eform-client/e2e/Page\ objects/OuterInnerResource
        cp -av eform-angular-outer-inner-resource-plugin/eform-client/wdio-headless-plugin-step2.conf.js eform-angular-frontend/eform-client/wdio-headless-plugin-step2.conf.js
        cp -av eform-angular-outer-inner-resource-plugin/eform-client/wdio-plugin-step2.conf.js eform-angular-frontend/eform-client/wdio-plugin-step2.conf.js
        mkdir -p eform-angular-frontend/eFormAPI/eFormAPI.Web/Plugins
        cp -av eform-angular-outer-inner-resource-plugin/eFormAPI/eFormAPI.Web/Plugins/OuterInnerResource.Pn eform-angular-frontend/eFormAPI/eFormAPI.Web/Plugins/OuterInnerResource.Pn
        cd eform-angular-frontend/eform-client && ../../eform-angular-outer-inner-resource-plugin/testinginstallpn.sh
    - name: Build frontend
      run: dotnet build eform-angular-frontend/eFormAPI/eFormAPI.sln
    - name: NPM install
      run: cd eform-angular-frontend/eform-client && npm install
    - name: NPM start
      run: cd eform-angular-frontend/eform-client && npm start > npm_log 2>&1 &
    - name: Sleep 75 seconds
      run: sleep 75
    - name: Dotnet run
      run: dotnet run --project eform-angular-frontend/eFormAPI/eFormAPI.Web/eFormAPI.Web.csproj > dotnet_log 2>&1 &
    - name: Sleep 75 seconds
      run: sleep 75
    - name: Configuration testing
      run: cd eform-angular-frontend/eform-client && npm run testheadless
    - name: Plugin testing
      run: cd eform-angular-frontend/eform-client && npm run testheadlessplugin
  service-build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Preparing debian-service checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: microting/eform-debian-service
        ref: stable
        path: eform-debian-service
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore eform-debian-service
    - name: Build
      run: dotnet build --configuration Release --no-restore eform-debian-service
    - name: Test
      run: dotnet test --no-restore --verbosity normal eform-debian-service
  outer-inner-resource-service-build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Preparing eform-service-outer-inner-resource-plugin checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: microting/eform-service-outer-inner-resource-plugin
        ref: stable
        path: eform-service-outer-inner-resource-plugin
    - uses: getong/mariadb-action@v1.1
      with:
        host port: 3306 # Optional, default value is 3306. The port of host
        container port: 3306 # Optional, default value is 3306. The port of container
        character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
        collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
        mariadb version: '10.4.10' # Optional, default value is "latest". The version of the MariaDB
        mysql database: 'some_test' # Optional, default value is "test". The specified database which will be create
        mysql root password: 'secretpassword' # Required if "mysql user" is empty, default is empty. The root superuser password
        mysql user: 'developer' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        mysql password: 'passwordtoo' # Required if "mysql user" exists. The password for the "mysql user"
    - name: Sleep 15 seconds
      run: sleep 15
    - uses: getong/rabbitmq-action@v1.2
      with:
        rabbitmq version: '3.8.9-management'
        host port: 5672
        rabbitmq user: 'admin'
        rabbitmq password: 'password'
        rabbitmq vhost: 'vhost_name'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore eform-service-outer-inner-resource-plugin
    - name: Build
      run: dotnet build --configuration Release --no-restore eform-service-outer-inner-resource-plugin
    - name: Unit Tests
      run: dotnet test --no-restore -c Release -v n eform-service-outer-inner-resource-plugin/ServiceOuterInnerResourcePlugin.Integration.Test/ServiceOuterInnerResourcePlugin.Integration.Test.csproj
  deploy:
    needs: [frontend-build, outer-inner-resource-build, service-build, outer-inner-resource-service-build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: main
    - name: 'Preparing Frontend checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: microting/eform-angular-frontend
        ref: stable
        path: eform-angular-frontend
    - name: 'Preparing items planning checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: microting/eform-angular-outer-inner-resource-plugin
        ref: stable
        path: eform-angular-outer-inner-resource-plugin
    - name: 'Preparing work order checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: microting/eform-angular-outer-inner-resource-plugin
        ref: stable
        path: eform-angular-outer-inner-resource-plugin
    - name: 'Preparing workflow checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: microting/eform-angular-workflow-plugin
        ref: stable
        path: eform-angular-workflow-plugin
    - name: 'Preparing backend configuration checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: microting/eform-backendconfiguration-plugin
        ref: stable
        path: eform-backendconfiguration-plugin
    - name: Copy dependencies
      run: |
        cp -av eform-angular-outer-inner-resource-plugin/eform-client/src/app/plugins/modules/outer-inner-resource-pn eform-angular-frontend/eform-client/src/app/plugins/modules/outer-inner-resource-pn
        mkdir -p eform-angular-frontend/eFormAPI/eFormAPI.Web/Plugins
        cd eform-angular-frontend/eform-client && ../../eform-angular-outer-inner-resource-plugin/testinginstallpn.sh
    - name: Get the version release
      id: get_release_version
      run: echo ::set-output name=VERSION::$(cd main && git describe --abbrev=0 --tags | cut -d "v" -f 2)
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(cd eform-angular-outer-inner-resource-plugin && git describe --abbrev=0 --tags | cut -d "v" -f 2)
    - name: Get the frontend version
      id: get_frontend_version
      run: echo ::set-output name=FRONTENDVERSION::$(cd eform-angular-frontend && git describe --abbrev=0 --tags | cut -d "v" -f 2)
    - name: Copy frontendfiles
      run: cp main/Dockerfile .
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the tagged Docker image
      run: docker build . -t microtingas/outer-inner-resource-container:latest -t microtingas/outer-inner-resource-container:${{ steps.get_release_version.outputs.VERSION }} --build-arg GITVERSION=${{ steps.get_frontend_version.outputs.FRONTENDVERSION }} --build-arg PLUGINVERSION=${{ steps.get_version.outputs.VERSION }}
    - name: Tag builds
      run: |-
        docker tag microtingas/outer-inner-resource-container:latest microtingas/outer-inner-resource-container:latest
        docker tag microtingas/outer-inner-resource-container:${{ steps.get_release_version.outputs.VERSION }} microtingas/outer-inner-resource-container:${{ steps.get_release_version.outputs.VERSION }}
    - name: Push the tagged Docker image
      run: docker push microtingas/outer-inner-resource-container:${{ steps.get_release_version.outputs.VERSION }}
    - name: Push the latest Docker image
      run: docker push microtingas/outer-inner-resource-container:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
  deploy-service:
    needs: [frontend-build, outer-inner-resource-build, service-build, outer-inner-resource-service-build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: main
    - name: 'Preparing Frontend checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: microting/eform-debian-service
        ref: stable
        path: eform-debian-service
    - name: 'Preparing items planning checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: microting/eform-service-outer-inner-resource-plugin
        ref: stable
        path: eform-service-outer-inner-resource-plugin
    - name: Get the version release
      id: get_release_version
      run: echo ::set-output name=VERSION::$(cd main && git describe --abbrev=0 --tags | cut -d "v" -f 2)
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(cd eform-service-outer-inner-resource-plugin && git describe --abbrev=0 --tags | cut -d "v" -f 2)
    - name: Get the service version
      id: get_service_version
      run: echo ::set-output name=FRONTENDVERSION::$(cd eform-debian-service && git describe --abbrev=0 --tags | cut -d "v" -f 2)
    - name: Copy Docker file
      run: cp main/Dockerfile-service Dockerfile
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the tagged Docker image
      run: docker build . -t microtingas/outer-inner-resource-service-container:latest -t microtingas/outer-inner-resource-service-container:${{ steps.get_release_version.outputs.VERSION }} --build-arg GITVERSION=${{ steps.get_service_version.outputs.FRONTENDVERSION }} --build-arg PLUGINVERSION=${{ steps.get_version.outputs.VERSION }}
    - name: Tag builds
      run: |-
        docker tag microtingas/outer-inner-resource-service-container:latest microtingas/outer-inner-resource-service-container:latest
        docker tag microtingas/outer-inner-resource-service-container:${{ steps.get_release_version.outputs.VERSION }} microtingas/outer-inner-resource-service-container:${{ steps.get_release_version.outputs.VERSION }}
    - name: Push the tagged Docker image
      run: docker push microtingas/outer-inner-resource-service-container:${{ steps.get_release_version.outputs.VERSION }}
    - name: Push the latest Docker image
      run: docker push microtingas/outer-inner-resource-service-container:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
